### ISSUE TITLE
Plugin stops working when using guardian beams on 1.19.2

### ISSUE THREAD

**Issue by haloflooder** [Exenco/Light-Show#5]
Was running a demo show on 1.19.2 and got this stacktrace

After you encounter the stacktrace. You can't stop or start the show again since it seems like the scheduler just died.

```
2022-09-14 08:51:05,548 Craft Scheduler Thread - 12 - Light-Show ERROR Recursive call to appender Async
[08:51:05 WARN]: [Light-Show] Plugin Light-Show v1.2.0 generated an exception while executing task 36
java.lang.NoSuchMethodError: 'java.util.UUID net.minecraft.world.entity.monster.EntityGuardian.cp()'
        at net.exenco.lightshow.util.api.GuardianBeamApi.spawn(GuardianBeamApi.java:64) ~[Light-Show-1.2.0.jar:?]
        at net.exenco.lightshow.show.stage.fixtures.MovingHeadFixture.applyState(MovingHeadFixture.java:174) ~[Light-Show-1.2.0.jar:?]
        at net.exenco.lightshow.show.stage.StageManager.lambda$updateFixtures$0(StageManager.java:148) ~[Light-Show-1.2.0.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[?:?]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765) ~[?:?]
        at net.exenco.lightshow.show.stage.StageManager.lambda$updateFixtures$1(StageManager.java:143) ~[Light-Show-1.2.0.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[?:?]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765) ~[?:?]
        at net.exenco.lightshow.show.stage.StageManager.lambda$updateFixtures$2(StageManager.java:141) ~[Light-Show-1.2.0.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.TreeMap$EntrySpliterator.forEachRemaining(TreeMap.java:3287) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290) ~[?:?]
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.helpComplete(ForkJoinPool.java:1223) ~[?:?]
        at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1915) ~[?:?]
        at java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:433) ~[?:?]
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:687) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:765) ~[?:?]
        at net.exenco.lightshow.show.stage.StageManager.updateFixtures(StageManager.java:139) ~[Light-Show-1.2.0.jar:?]
        at net.exenco.lightshow.show.receiver.ServerReceiver$1.run(ServerReceiver.java:84) ~[Light-Show-1.2.0.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.2.jar:git-Purpur-1762]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.2.jar:git-Purpur-1762]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Exenco** [comment]
Hey, sorry for letting you wait so long.
Thats an issue with the plugin being built for 1.19 and you using 1.19.2. I will try finding time to look whether it is possible to update to the later versions.
For now, please use 1.19.

**Comment by haloflooder** [comment]
Not a problem!

We're currently maintaining our own fork of this plugin for now and implemented multi-version support! Not sure if we'll do a pull request because we restructured the project quite a bit but I feel like we can talk about it if you're interested in it :)

**Comment by Exenco** [comment]
Oh absolutely, any improvement or just alternative is very welcome! You can find me on the [Discord Server](https://discord.gg/cDzyUUuwaH).

**Comment by Exenco** [comment]
Update out. As mentioned, if there is anything hit me up on Discord.
